version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: lms_postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_pass
    ports:
      - "5432:5432"
    volumes:
      - lms_data:/var/lib/postgresql/data

volumes:
  lms_data: