spring:
  application:
    name: lms
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: lms_user
    password: lms_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  springdoc:
    api-docs:
      path:/v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  scheduler:
    delete-old-schedules:
      cron: "@daily"
